name: Generate Summary

on:
    push:
        paths:
            - 'docs/tests/**/*.md'
            - 'scripts/generate-summary.js'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    generate-summary:
        runs-on: ubuntu-latest

        steps:
        - 
            name: Checkout code
            uses: actions/checkout@v3

        - 
            name: Setup Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '18'

        -
            name: Generate Summary.md
            working-directory: ${{ github.workspace }}
            run: npm run gen-summary

        -
            name: Commit and push updated Summary.md
            run: |
                git config --global user.name 'github-actions[bot]'
                git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                git add docs/tests/frontend_tests/Summary.md
                git add docs/tests/backend_tests/Summary.md
                git commit -m 'Auto-update Summary.md' || echo "No changes to commit"
                git push
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}